// error map
const errors = {
    12345: 'Example error'
}

// transforms an error from axios to a pretty error message for the client
export const getErrorMessage = (error) => {
    if (error.response) {
        // error generated by the api
        console.log(error.response)
        if (error.response.errorCode in errors) {
            return errors[error.response.errorCode]
        }

        return 'Unknown error'
    } else if (error.request) {
        // no response received
        console.log(error.request)
        return 'Internal server error'
    } else {
        // unexpected
        console.log(error.message)
        return 'Unexpected error'
    }
}
