// error map
const errors = {
    12345: 'Example error',
    21604: 'Acest token nu este valid',
    25400: 'Numele de utilizator există deja',
}

// transforms an error from axios to a pretty error message for the client
export const getErrorMessage = (error) => {
    if (error.response) {
        // error generated by the api
        console.log(error.response)
        if (error.response.data.errorCode in errors) {
            return errors[error.response.data.errorCode]
        }

        return 'Eroare necunoscută'
    } else if (error.request) {
        // no response received
        console.log(error.request)
        return 'Eroare internă'
    } else {
        // unexpected
        console.log(error.message)
        return 'Eroare neașteptată'
    }
}

// for testing only
export const delay = (ms) => new Promise((res) => setTimeout(res, ms))
