export { default as AccountSettings } from './AccountSettings'
export { default as History } from './History'
export { default as Notifications } from './Notifications'
export { default as ProfileSettings } from './ProfileSettings'
export { default as Settings } from './Settings'
