import os
from enum import Enum

ACCOUNT_VERIFICATION_ROUTE = "verify_account"
CHANGE_REQUEST_ROUTE = "verify_change"

TEMPLATES_DIR_PATH = os.path.join(os.path.dirname(__file__), "templates")
ACCOUNT_VERIFICATION_FILE_NAME = "account_verification.html"
CHANGE_REQUEST_FILE_NAME = "change_request.html"

ACCOUNT_VERIFICATION_SUBJECT = "Account Verification Requested"
CHANGE_REQUEST_SUBJECT = "Account Change Requested"


class ErrorCodes(Enum):
    SMTP_CONNECTION_FAILED = 20600
    SMTP_TTLS_FAILED = 20601
    SMTP_LOGIN_FAILED = 20602
    SMTP_SEND_EMAIL_FAILED = 20603
    ACCOUNT_VERIFICATION_TEMPLATE_READING_FAILED = 20604
    ACCOUNT_VERIFICATION_TEMPLATE_FORMATTING_FAILED = 20605
    REQUEST_CHANGE_TEMPLATE_READING_FAILED = 20606
    REQUEST_CHANGE_TEMPLATE_FORMATTING_FAILED = 20607
