from enum import Enum
from fastapi import status

TIMEOUT_LIMIT = 3
DESIRED_EMAIL_CHANGE_TOKEN_TYPE = "emailChange"


class ErrorCodes(Enum):
    DB_CONNECTION_FAILURE = 25900
    FAILED_TO_GET_TOKEN_TYPE = 25901
    TOKEN_NOT_FOUND = 25902
    FAILED_TO_GET_USER_ID = 25903
    USER_NOT_FOUND = 25904
    FAILED_TO_UPDATE_EMAIL = 25905
    FAILED_TO_DESTROY_TOKENS = 25906
    INVALID_TOKEN_TYPE = 25907
    TOKEN_GENERATION_REQUEST_FAILED = 25908
    ACCOUNT_VERIFICATION_REQUEST_FAILED = 25909


ErrorCodesToHTTPCodesMapping: dict[int, int] = {
    ErrorCodes.TOKEN_NOT_FOUND.value: status.HTTP_404_NOT_FOUND,
    ErrorCodes.USER_NOT_FOUND.value: status.HTTP_404_NOT_FOUND,
    ErrorCodes.INVALID_TOKEN_TYPE.value: status.HTTP_403_FORBIDDEN,
}
